name: Release

on:
  push:
    tags:
      - 'v*' # 当你推送以 v 开头的标签时触发，如 v1.0.0
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    name: Build for ARMv8
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aarch64-unknown-linux-musl]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build Binary
        run: cross build --target ${{ matrix.target }} --release

      - name: Post-process Binary (Strip & Rename)
        run: |
          # 进一步确保符号表被移除（双重保险）
          # 注意：cross 镜像内通常已有对应的 strip 工具
          cd target/${{ matrix.target }}/release/
          mv david david-openwrt-armv8
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: david-aarch64
          path: target/${{ matrix.target }}/release/david-openwrt-armv8

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/david-openwrt-armv8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
